/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nivalit.invoiceninja.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id The bank integration hashed id
 * @param companyId The company hashed id
 * @param userId The user hashed id
 * @param providerBankName The providers bank name
 * @param bankAccountId The bank account id
 * @param bankAccountName The name of the account
 * @param bankAccountNumber The account number
 * @param bankAccountStatus The status of the bank account
 * @param bankAccountType The type of account
 * @param balance The current bank balance if available
 * @param currency iso_3166_3 code
 */


data class BankIntegration (

    /* The bank integration hashed id */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* The company hashed id */
    @Json(name = "company_id")
    val companyId: kotlin.String? = null,

    /* The user hashed id */
    @Json(name = "user_id")
    val userId: kotlin.String? = null,

    /* The providers bank name */
    @Json(name = "provider_bank_name")
    val providerBankName: kotlin.String? = null,

    /* The bank account id */
    @Json(name = "bank_account_id")
    val bankAccountId: kotlin.String? = null,

    /* The name of the account */
    @Json(name = "bank_account_name")
    val bankAccountName: kotlin.String? = null,

    /* The account number */
    @Json(name = "bank_account_number")
    val bankAccountNumber: kotlin.String? = null,

    /* The status of the bank account */
    @Json(name = "bank_account_status")
    val bankAccountStatus: kotlin.String? = null,

    /* The type of account */
    @Json(name = "bank_account_type")
    val bankAccountType: kotlin.String? = null,

    /* The current bank balance if available */
    @Json(name = "balance")
    val balance: java.math.BigDecimal? = null,

    /* iso_3166_3 code */
    @Json(name = "currency")
    val currency: kotlin.String? = null

)

