/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nivalit.invoiceninja.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id The hashed id of the client gateway token
 * @param companyId The hashed id of the company
 * @param clientId The hashed_id of the client
 * @param token The payment token
 * @param routingNumber THe bank account routing number
 * @param companyGatewayId The hashed id of the company gateway
 * @param isDefault Flag determining if the token is the default payment method
 */


data class ClientGatewayToken (

    /* The hashed id of the client gateway token */
    @field:JsonProperty("id")
    val id: kotlin.String? = null,

    /* The hashed id of the company */
    @field:JsonProperty("company_id")
    val companyId: kotlin.String? = null,

    /* The hashed_id of the client */
    @field:JsonProperty("client_id")
    val clientId: kotlin.String? = null,

    /* The payment token */
    @field:JsonProperty("token")
    val token: kotlin.String? = null,

    /* THe bank account routing number */
    @field:JsonProperty("routing_number")
    val routingNumber: kotlin.String? = null,

    /* The hashed id of the company gateway */
    @field:JsonProperty("company_gateway_id")
    val companyGatewayId: kotlin.String? = null,

    /* Flag determining if the token is the default payment method */
    @field:JsonProperty("is_default")
    val isDefault: kotlin.Boolean? = null

)

