/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nivalit.invoiceninja.models

import com.nivalit.invoiceninja.models.ClientContact
import com.nivalit.invoiceninja.models.CompanySettings

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id The unique identifier of the client
 * @param userId The unique identifier of the user who created the client
 * @param companyId The unique identifier of the company the client belongs to
 * @param contacts 
 * @param name The name of the client company or organization
 * @param website The website URL of the client company or organization
 * @param privateNotes Notes that are only visible to the user who created the client
 * @param clientHash A unique hash value for the client
 * @param industryId The unique identifier of the industry the client operates in
 * @param sizeId The unique identifier for the size category of the client company or organization
 * @param address1 First line of the client's address
 * @param address2 Second line of the client's address, if needed
 * @param city The city the client is located in
 * @param state The state, province, or locality the client is located in
 * @param postalCode The postal code or ZIP code of the client
 * @param phone The client's phone number
 * @param countryId The unique identifier of the client's country
 * @param customValue1 A custom field for storing additional information
 * @param customValue2 A custom field for storing additional information
 * @param customValue3 A custom field for storing additional information
 * @param customValue4 A custom field for storing additional information
 * @param vatNumber The client's VAT (Value Added Tax) number, if applicable
 * @param idNumber A unique identification number for the client, such as a tax ID or business registration number
 * @param number A system-assigned unique number for the client, typically used for invoicing purposes
 * @param shippingAddress1 First line of the client's shipping address
 * @param shippingAddress2 Second line of the client's shipping address, if needed
 * @param shippingCity The city of the client's shipping address
 * @param shippingState The state, province, or locality of the client's shipping address
 * @param shippingPostalCode The postal code or ZIP code of the client's shipping address
 * @param shippingCountryId The unique identifier of the country for the client's shipping address
 * @param isDeleted A boolean value indicating whether the client has been deleted or not
 * @param balance The outstanding balance the client owes
 * @param paidToDate The total amount the client has paid to date
 * @param creditBalance The available credit balance for the client to use on future purchases
 * @param lastLogin The timestamp of the client's last login
 * @param createdAt The timestamp when the client was created
 * @param updatedAt The timestamp when the client was last updated
 * @param settings 
 */


data class Client (

    /* The unique identifier of the client */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* The unique identifier of the user who created the client */
    @Json(name = "user_id")
    val userId: kotlin.String? = null,

    /* The unique identifier of the company the client belongs to */
    @Json(name = "company_id")
    val companyId: kotlin.String? = null,

    @Json(name = "contacts")
    val contacts: kotlin.collections.List<ClientContact>? = null,

    /* The name of the client company or organization */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* The website URL of the client company or organization */
    @Json(name = "website")
    val website: kotlin.String? = null,

    /* Notes that are only visible to the user who created the client */
    @Json(name = "private_notes")
    val privateNotes: kotlin.String? = null,

    /* A unique hash value for the client */
    @Json(name = "client_hash")
    val clientHash: kotlin.String? = null,

    /* The unique identifier of the industry the client operates in */
    @Json(name = "industry_id")
    val industryId: java.math.BigDecimal? = null,

    /* The unique identifier for the size category of the client company or organization */
    @Json(name = "size_id")
    val sizeId: java.math.BigDecimal? = null,

    /* First line of the client's address */
    @Json(name = "address1")
    val address1: kotlin.String? = null,

    /* Second line of the client's address, if needed */
    @Json(name = "address2")
    val address2: kotlin.String? = null,

    /* The city the client is located in */
    @Json(name = "city")
    val city: kotlin.String? = null,

    /* The state, province, or locality the client is located in */
    @Json(name = "state")
    val state: kotlin.String? = null,

    /* The postal code or ZIP code of the client */
    @Json(name = "postal_code")
    val postalCode: kotlin.String? = null,

    /* The client's phone number */
    @Json(name = "phone")
    val phone: kotlin.String? = null,

    /* The unique identifier of the client's country */
    @Json(name = "country_id")
    val countryId: java.math.BigDecimal? = null,

    /* A custom field for storing additional information */
    @Json(name = "custom_value1")
    val customValue1: kotlin.String? = null,

    /* A custom field for storing additional information */
    @Json(name = "custom_value2")
    val customValue2: kotlin.String? = null,

    /* A custom field for storing additional information */
    @Json(name = "custom_value3")
    val customValue3: kotlin.String? = null,

    /* A custom field for storing additional information */
    @Json(name = "custom_value4")
    val customValue4: kotlin.String? = null,

    /* The client's VAT (Value Added Tax) number, if applicable */
    @Json(name = "vat_number")
    val vatNumber: kotlin.String? = null,

    /* A unique identification number for the client, such as a tax ID or business registration number */
    @Json(name = "id_number")
    val idNumber: kotlin.String? = null,

    /* A system-assigned unique number for the client, typically used for invoicing purposes */
    @Json(name = "number")
    val number: kotlin.String? = null,

    /* First line of the client's shipping address */
    @Json(name = "shipping_address1")
    val shippingAddress1: kotlin.String? = null,

    /* Second line of the client's shipping address, if needed */
    @Json(name = "shipping_address2")
    val shippingAddress2: kotlin.String? = null,

    /* The city of the client's shipping address */
    @Json(name = "shipping_city")
    val shippingCity: kotlin.String? = null,

    /* The state, province, or locality of the client's shipping address */
    @Json(name = "shipping_state")
    val shippingState: kotlin.String? = null,

    /* The postal code or ZIP code of the client's shipping address */
    @Json(name = "shipping_postal_code")
    val shippingPostalCode: kotlin.String? = null,

    /* The unique identifier of the country for the client's shipping address */
    @Json(name = "shipping_country_id")
    val shippingCountryId: java.math.BigDecimal? = null,

    /* A boolean value indicating whether the client has been deleted or not */
    @Json(name = "is_deleted")
    val isDeleted: kotlin.Boolean? = null,

    /* The outstanding balance the client owes */
    @Json(name = "balance")
    val balance: kotlin.Float? = null,

    /* The total amount the client has paid to date */
    @Json(name = "paid_to_date")
    val paidToDate: kotlin.Float? = null,

    /* The available credit balance for the client to use on future purchases */
    @Json(name = "credit_balance")
    val creditBalance: kotlin.Float? = null,

    /* The timestamp of the client's last login */
    @Json(name = "last_login")
    val lastLogin: java.math.BigDecimal? = null,

    /* The timestamp when the client was created */
    @Json(name = "created_at")
    val createdAt: java.math.BigDecimal? = null,

    /* The timestamp when the client was last updated */
    @Json(name = "updated_at")
    val updatedAt: java.math.BigDecimal? = null,

    @Json(name = "settings")
    val settings: CompanySettings? = null

)

