/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nivalit.invoiceninja.models

import com.nivalit.invoiceninja.models.Client

import com.squareup.moshi.Json

/**
 * 
 *
 * @param `data` 
 */


data class ClientWrapped (

    @Json(name = "data")
    val `data`: Client? = null

)

