/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nivalit.invoiceninja.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id The document hashed id
 * @param userId The user hashed id
 * @param assignedUserId The assigned user hashed id
 * @param projectId The project associated with this document
 * @param vendorId The vendor associated with this documents
 * @param name The document name
 * @param url The document url
 * @param preview The document preview url
 * @param type The document type
 * @param disk The document disk
 * @param hash The document hashed
 * @param isDeleted Flag to determine if the document is deleted
 * @param isDefault Flag to determine if the document is a default doc
 * @param createdAt Timestamp
 * @param updatedAt Timestamp
 * @param deletedAt Timestamp
 */


data class Document (

    /* The document hashed id */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* The user hashed id */
    @Json(name = "user_id")
    val userId: kotlin.String? = null,

    /* The assigned user hashed id */
    @Json(name = "assigned_user_id")
    val assignedUserId: kotlin.String? = null,

    /* The project associated with this document */
    @Json(name = "project_id")
    val projectId: kotlin.String? = null,

    /* The vendor associated with this documents */
    @Json(name = "vendor_id")
    val vendorId: kotlin.String? = null,

    /* The document name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* The document url */
    @Json(name = "url")
    val url: kotlin.String? = null,

    /* The document preview url */
    @Json(name = "preview")
    val preview: kotlin.String? = null,

    /* The document type */
    @Json(name = "type")
    val type: kotlin.String? = null,

    /* The document disk */
    @Json(name = "disk")
    val disk: kotlin.String? = null,

    /* The document hashed */
    @Json(name = "hash")
    val hash: kotlin.String? = null,

    /* Flag to determine if the document is deleted */
    @Json(name = "is_deleted")
    val isDeleted: kotlin.Boolean? = null,

    /* Flag to determine if the document is a default doc */
    @Json(name = "is_default")
    val isDefault: kotlin.Boolean? = null,

    /* Timestamp */
    @Json(name = "created_at")
    val createdAt: java.math.BigDecimal? = null,

    /* Timestamp */
    @Json(name = "updated_at")
    val updatedAt: java.math.BigDecimal? = null,

    /* Timestamp */
    @Json(name = "deleted_at")
    val deletedAt: java.math.BigDecimal? = null

)

