/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nivalit.invoiceninja.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param subject The email template subject
 * @param body The email template body
 * @param entity 
 * @param entityId 
 * @param template 
 */


data class GetShowTemplateRequest (

    /* The email template subject */
    @field:JsonProperty("subject")
    val subject: kotlin.String? = null,

    /* The email template body */
    @field:JsonProperty("body")
    val body: kotlin.String? = null,

    @field:JsonProperty("entity")
    val entity: kotlin.String? = null,

    @field:JsonProperty("entity_id")
    val entityId: kotlin.String? = null,

    @field:JsonProperty("template")
    val template: kotlin.String? = null

)

