/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nivalit.invoiceninja.models

import com.nivalit.invoiceninja.models.CreditPaymentable
import com.nivalit.invoiceninja.models.InvoicePaymentable
import com.nivalit.invoiceninja.models.Paymentable

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id The payment hashed id
 * @param clientId The client hashed id
 * @param invitationId The invitation hashed id
 * @param clientContactId The client contact hashed id
 * @param userId The user hashed id
 * @param typeId The Payment Type ID
 * @param date The Payment date
 * @param transactionReference The transaction reference as defined by the payment gateway
 * @param assignedUserId The assigned user hashed id
 * @param privateNotes The private notes of the payment
 * @param isManual Flags whether the payment was made manually or processed via a gateway
 * @param isDeleted Defines if the payment has been deleted
 * @param amount The amount of this payment
 * @param refunded The refunded amount of this payment
 * @param updatedAt Timestamp
 * @param archivedAt Timestamp
 * @param companyGatewayId The company gateway id
 * @param paymentables 
 * @param invoices 
 * @param credits 
 * @param number The payment number - is a unique alpha numeric number per payment per company
 */


data class Payment (

    /* The payment hashed id */
    @field:JsonProperty("id")
    val id: kotlin.String? = null,

    /* The client hashed id */
    @field:JsonProperty("client_id")
    val clientId: kotlin.String? = null,

    /* The invitation hashed id */
    @field:JsonProperty("invitation_id")
    val invitationId: kotlin.String? = null,

    /* The client contact hashed id */
    @field:JsonProperty("client_contact_id")
    val clientContactId: kotlin.String? = null,

    /* The user hashed id */
    @field:JsonProperty("user_id")
    val userId: kotlin.String? = null,

    /* The Payment Type ID */
    @field:JsonProperty("type_id")
    val typeId: kotlin.String? = null,

    /* The Payment date */
    @field:JsonProperty("date")
    val date: kotlin.String? = null,

    /* The transaction reference as defined by the payment gateway */
    @field:JsonProperty("transaction_reference")
    val transactionReference: kotlin.String? = null,

    /* The assigned user hashed id */
    @field:JsonProperty("assigned_user_id")
    val assignedUserId: kotlin.String? = null,

    /* The private notes of the payment */
    @field:JsonProperty("private_notes")
    val privateNotes: kotlin.String? = null,

    /* Flags whether the payment was made manually or processed via a gateway */
    @field:JsonProperty("is_manual")
    val isManual: kotlin.Boolean? = null,

    /* Defines if the payment has been deleted */
    @field:JsonProperty("is_deleted")
    val isDeleted: kotlin.Boolean? = null,

    /* The amount of this payment */
    @field:JsonProperty("amount")
    val amount: java.math.BigDecimal? = null,

    /* The refunded amount of this payment */
    @field:JsonProperty("refunded")
    val refunded: java.math.BigDecimal? = null,

    /* Timestamp */
    @field:JsonProperty("updated_at")
    val updatedAt: java.math.BigDecimal? = null,

    /* Timestamp */
    @field:JsonProperty("archived_at")
    val archivedAt: java.math.BigDecimal? = null,

    /* The company gateway id */
    @field:JsonProperty("company_gateway_id")
    val companyGatewayId: kotlin.String? = null,

    @field:JsonProperty("paymentables")
    val paymentables: Paymentable? = null,

    /*  */
    @field:JsonProperty("invoices")
    val invoices: kotlin.collections.List<InvoicePaymentable>? = null,

    /*  */
    @field:JsonProperty("credits")
    val credits: kotlin.collections.List<CreditPaymentable>? = null,

    /* The payment number - is a unique alpha numeric number per payment per company */
    @field:JsonProperty("number")
    val number: kotlin.String? = null

)

