/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nivalit.invoiceninja.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param numDays The payment term length in days
 * @param name The payment term length in string format
 * @param createdAt Timestamp
 * @param updatedAt Timestamp
 * @param archivedAt Timestamp
 */


data class PaymentTerm (

    /* The payment term length in days */
    @field:JsonProperty("num_days")
    val numDays: kotlin.Int? = null,

    /* The payment term length in string format */
    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Timestamp */
    @field:JsonProperty("created_at")
    val createdAt: java.math.BigDecimal? = null,

    /* Timestamp */
    @field:JsonProperty("updated_at")
    val updatedAt: java.math.BigDecimal? = null,

    /* Timestamp */
    @field:JsonProperty("archived_at")
    val archivedAt: java.math.BigDecimal? = null

)

