/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nivalit.invoiceninja.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id The account hashed id
 * @param companyId The company hashed id
 * @param userId The user_id hashed id
 * @param clientId The client_id hashed id
 * @param eventId The Log Type ID
 * @param categoryId The Category Type ID
 * @param typeId The Type Type ID
 * @param log The json object of the error
 * @param updatedAt Timestamp
 * @param createdAt Timestamp
 */


data class SystemLog (

    /* The account hashed id */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* The company hashed id */
    @Json(name = "company_id")
    val companyId: kotlin.String? = null,

    /* The user_id hashed id */
    @Json(name = "user_id")
    val userId: kotlin.String? = null,

    /* The client_id hashed id */
    @Json(name = "client_id")
    val clientId: kotlin.String? = null,

    /* The Log Type ID */
    @Json(name = "event_id")
    val eventId: kotlin.Int? = null,

    /* The Category Type ID */
    @Json(name = "category_id")
    val categoryId: kotlin.Int? = null,

    /* The Type Type ID */
    @Json(name = "type_id")
    val typeId: kotlin.Int? = null,

    /* The json object of the error */
    @Json(name = "log")
    val log: kotlin.Any? = null,

    /* Timestamp */
    @Json(name = "updated_at")
    val updatedAt: kotlin.String? = null,

    /* Timestamp */
    @Json(name = "created_at")
    val createdAt: kotlin.String? = null

)

