/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nivalit.invoiceninja.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id The hashed id of the user
 * @param firstName The first name of the user
 * @param lastName The last name of the user
 * @param email The users email address
 * @param phone The users phone number
 * @param signature The users sign off signature
 * @param avatar The users avatar
 * @param acceptedTermsVersion The version of the invoice ninja terms that has been accepted by the user
 * @param oauthUserId The provider id of the oauth entity
 * @param oauthProviderId The oauth entity id
 */


data class User (

    /* The hashed id of the user */
    @field:JsonProperty("id")
    val id: kotlin.String? = null,

    /* The first name of the user */
    @field:JsonProperty("first_name")
    val firstName: kotlin.String? = null,

    /* The last name of the user */
    @field:JsonProperty("last_name")
    val lastName: kotlin.String? = null,

    /* The users email address */
    @field:JsonProperty("email")
    val email: kotlin.String? = null,

    /* The users phone number */
    @field:JsonProperty("phone")
    val phone: kotlin.String? = null,

    /* The users sign off signature */
    @field:JsonProperty("signature")
    val signature: kotlin.String? = null,

    /* The users avatar */
    @field:JsonProperty("avatar")
    val avatar: kotlin.String? = null,

    /* The version of the invoice ninja terms that has been accepted by the user */
    @field:JsonProperty("accepted_terms_version")
    val acceptedTermsVersion: kotlin.String? = null,

    /* The provider id of the oauth entity */
    @field:JsonProperty("oauth_user_id")
    val oauthUserId: kotlin.String? = null,

    /* The oauth entity id */
    @field:JsonProperty("oauth_provider_id")
    val oauthProviderId: kotlin.String? = null

)

